service: subdomain-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  register:
    handler: subdomainMapping/register.register
    events:
      - http:
          path: subdomainMapping
          method: post
          cors: true

  list:
    handler: subdomainMapping/isAvailable.isAvailable
    events:
      - http:
          path: subdomainMapping/{hostname}
          method: get
          cors: true

  get:
    handler: subdomainMapping/get.get
    events:
      - http:
          path: subdomainMapping/{hostname}
          method: get
          cors: true

  update:
    handler: subdomainMapping/update.update
    events:
      - http:
          path: subdomainMapping/{id}
          method: put
          cors: true

  delete:
    handler: subdomainMapping/delete.delete
    events:
      - http:
          path: subdomainMapping/{id}
          method: delete
          cors: true

resources:
  Resources:
    subdomainMappingDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
